// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5GFw61b9nzw8JF1W0k4LrcO0uGogaMcg',
    appId: '1:749536324672:android:0722f51f467bf0465b43a5',
    messagingSenderId: '749536324672',
    projectId: 'zeeu-f8a0e',
    storageBucket: 'zeeu-f8a0e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNQ4Ev74vDXWcfVPdMwPDkKN8g3K9vTYo',
    appId: '1:749536324672:ios:3fa6346ed962cc665b43a5',
    messagingSenderId: '749536324672',
    projectId: 'zeeu-f8a0e',
    storageBucket: 'zeeu-f8a0e.appspot.com',
    iosClientId: '749536324672-7slao0pgbit6a5lurc9gnjitetmkcb2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.zeeu',
  );
}
